### ISSUE TITLE
LSP Features

### ISSUE THREAD

**Issue by SpontanCombust** [SpontanCombust/witcherscript-ide#28]
This is a tracking issue monitoring progress on Language Server Protocol features that could be implemented into WitcherScript IDE.

Features below are listed in the order of appearance on protocol's specification page:
- [ ] [Goto Declaration Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_declaration) #13 
- [ ] [Goto Definition Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition) #13
- [ ] [Goto Type Definition Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_typeDefinition) #13
- [ ] ~~[Goto Implementation Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_typeDefinition)~~ - WitcherScript does not have interface types

- [ ] [Find References Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_references)
- [ ] [Prepare Type Hierarchy Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareTypeHierarchy)
- [ ] [Type Hierarchy Supertypes](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#typeHierarchy_supertypes)
- [ ] [Type Hierarchy Subtypes](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#typeHierarchy_subtypes)

- [ ] [Document Highlights Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight) 

- [ ] [Hover Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover) #7 

- [ ] [Code Lens Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeLens)

- [ ] [Document Symbols Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol) #26 

- [ ] [Semantic Tokens](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens)

- [ ] [Inlay Hint Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint)

- [ ] [Completion Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion) #20 

- [ ] [Signature Help Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_signatureHelp)

- [ ] [Code Action Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction)

- [ ] [Rename Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rename)

- [ ] [Workspace Symbols Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_symbol)
